# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='difficulty',
            field=models.CharField(choices=[('any', 'Any'), ('beg', 'Beginner'), ('med', 'Medium'), ('adv', 'Advanced')], default='any', max_length=3),
        ),
    ]
