# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190512_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_premium',
            new_name='is_gold',
        ),
    ]
