# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import langscape.articles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190512_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, validators=[langscape.articles.validators.validate_article]),
        ),
    ]
